Add icon for ul, ol and code block
Jaagrav/Cordion pull request #1
Opened 2021-02-10 18:31 UTC by pronayguha13

Added icon in place of Text in the Editor.

2021-02-10 19:53 UTC, Jaagrav requested changes
Use material icons instead, check diff comments.

2021-02-10 19:53 UTC, Jaagrav commented on src/pages/Home/components/Editor/index.js
> +import code from "../../../../assets/icons/code-block.png";
So I am using Material UI for this project, if you can please import a suitable icon from @material-ui/icons instead.

2021-02-10 19:53 UTC, Jaagrav commented on src/pages/Home/components/Editor/index.js
> +        </Button>
You can look for suitable icons [here](https://material-ui.com/components/material-icons/)

2021-02-11 07:02 UTC, pronayguha13 commented on src/pages/Home/components/Editor/index.js
> +import code from "../../../../assets/icons/code-block.png";
Okay sure I'll definitely do the needful

2021-02-11 19:02 UTC, pronayguha13 commented
Added icons from material-ui but there may be some issue related to git.
Please check them first.

2021-02-11 19:11 UTC, closed without merging